version: 2
updates:
  # Check for Dockerfile updates (Base images like eclipse-temurin)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"